import {
  Antenna,
  Award,
  BadgeCheck,
  Blocks,
  BrainCircuit,
  Building2,
  Camera,
  Clapperboard,
  Compass,
  Cpu,
  Drone,
  Fingerprint,
  Gauge,
  GraduationCap,
  Handshake,
  Headphones,
  Landmark,
  Layers,
  Lightbulb,
  type LucideIcon,
  Megaphone,
  MonitorPlay,
  Network,
  Radio,
  Rocket,
  Satellite,
  ScanFace,
  Search,
  Server,
  ShieldCheck,
  Sparkles,
  Target,
  Timer,
  Users,
  Video,
} from "lucide-react";

/**
 * Central icon registry so content data can reference icons by string key
 * without importing lucide into every data file.
 */
export const ICONS: Record<string, LucideIcon> = {
  antenna: Antenna,
  award: Award,
  badgeCheck: BadgeCheck,
  blocks: Blocks,
  brainCircuit: BrainCircuit,
  building: Building2,
  camera: Camera,
  clapperboard: Clapperboard,
  compass: Compass,
  cpu: Cpu,
  drone: Drone,
  fingerprint: Fingerprint,
  gauge: Gauge,
  graduationCap: GraduationCap,
  handshake: Handshake,
  headphones: Headphones,
  landmark: Landmark,
  layers: Layers,
  lightbulb: Lightbulb,
  megaphone: Megaphone,
  monitorPlay: MonitorPlay,
  network: Network,
  radio: Radio,
  rocket: Rocket,
  satellite: Satellite,
  scanFace: ScanFace,
  search: Search,
  server: Server,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  target: Target,
  timer: Timer,
  users: Users,
  video: Video,
};

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Sparkles;
}
