export const TABLE_TAGS: Record<string, string[]> = {
  content_blocks: ["blocks"],
  nav_items: ["nav"],
  solutions: ["solutions"],
  cross_cutting_offerings: ["solutions"],
  service_wings: ["solutions"],
  capabilities: ["capabilities"],
  standing_capabilities: ["capabilities"],
  network_regions: ["capabilities"],
  deploy_steps: ["capabilities"],
  core_values: ["about"],
  why_choose_reasons: ["about"],
  timeline_entries: ["about"],
  sector_groups: ["about"],
  stats: ["home", "about"],
  case_studies: ["impact"],
  featured_projects: ["impact"],
  impact_sectors: ["impact"],
  clients: ["impact"],
  testimonials: ["impact"],
  programmes: ["programmes"],
  insights: ["insights"],
  form_options: ["forms"],
  media_assets: ["media"],
};
